name: ultrasound
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  gsheets: ^0.4.2
  shared_preferences: ^2.0.15
  firebase_auth: ^4.2.3
  fluttertoast: ^8.1.2
  cloud_firestore: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/pcos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/pcos.png
  